
mybatis:
  config-location: classpath:mybatis/mybatis.xml                                      #mybatis配置文件所在路径
  type-aliases-package: com.wfl.emps.enity                                      #所有Enity别名所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                                                   # mapper映射文件
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                                         #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                                           #mysql驱动包
    url: jdbc:mysql://localhost:3306/cruddemo?useSSL=false&serverTimezone=UTC            #数据库名称
    username: root
    password: root123
    dbcp2:
      min-idle: 5                                                                        #数据库连接池的最小连接数
      initial-size: 5                                                                     #初始化连接数
      max-total: 5                                                                        #最大连接数
      max-wait-millis: 200                                                                #等待连接获取的最大超时时间
  thymeleaf:
    cache: false
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true